services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: food-delivery:latest

    container_name: food-delivery

    restart: unless-stopped

    ports:
      - "80:8083"

    environment:
      SERVER_PORT: "8083"
      SPRING_PROFILES_ACTIVE: "default"