# SonarQube Server details (Only necessary if not using Jenkins withSonarQubeEnv or Maven wrapper defaults)
sonar.projectKey=fooddeliveryapp
sonar.projectName=Food Delivery App
sonar.projectVersion=1.0

# Path to source directories (required)
sonar.sources=src/main/java

# Path to test directories
sonar.tests=src/test/java

# Language
sonar.language=java

# Compiled class files
sonar.java.binaries=target/classes

# Coverage reporting (if Jacoco gets added)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
